services:
    _defaults:
        public: true


    numero2_brevo_member_sync.listener.data_container.member:
        class: numero2\BrevoMemberSyncBundle\EventListener\DataContainer\MemberListener
        arguments:
            - '@numero2_brevo_member_sync.listener.hooks.brevo'

    numero2_brevo_member_sync.listener.data_container.module:
        class: numero2\BrevoMemberSyncBundle\EventListener\DataContainer\ModuleListener


    numero2_brevo_member_sync.listener.hooks.brevo:
        class: numero2\BrevoMemberSyncBundle\EventListener\Hooks\BrevoListener
